# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- azure

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
- task: AzureSpringCloud@0
  inputs:
    azureSubscription: 'springdemoconnection'
    Action: 'Deploy'
    AzureSpringCloud: kyliespringdemo
    AppName: customers-service
    DeploymentName: green
    UseStagingDeployment: true
    Package: /home/vsts/work/1/s/spring-petclinic-customers-service/target/spring-petclinic-customers-service-2.3.6.jar
- task: AzureSpringCloud@0
  inputs:
    azureSubscription: 'springdemoconnection'
    Action: 'Set Production'
    AzureSpringCloud: kyliespringdemo
    AppName: customers-service
    UseStagingDeployment: true